# Generated by Django 5.1.7 on 2025-03-25 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('detected_time', models.DateTimeField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('video_frame_folder', models.CharField(max_length=255)),
                ('key_frame', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_time', models.DateTimeField()),
                ('dispatched_time', models.DateTimeField()),
                ('dispatched_police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_accidents', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='main.accident')),
            ],
        ),
    ]
