# Generated by Django 5.1.7 on 2025-03-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_policeofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='dispatched_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_accidents', to='main.policeofficer'),
        ),
    ]
