# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_accident_dispatched_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
