# Generated by Django 5.1.7 on 2025-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_accident_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv_id', models.CharField(max_length=50, unique=True)),
                ('road_section', models.CharField(max_length=255)),
                ('px', models.FloatField()),
                ('py', models.FloatField()),
                ('site_url', models.URLField()),
                ('status', models.CharField(max_length=50)),
                ('agency_codes', models.CharField(max_length=50)),
                ('local_call_service', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=50)),
                ('county_code', models.CharField(max_length=50)),
                ('area_code', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('hotspot', models.BooleanField(default=False)),
                ('mjpeg_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
