# Generated by Django 5.1.7 on 2025-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cctv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='summary',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='scene_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cctv_accident/'),
        ),
    ]
